# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b29216aed8d9ba73423c54a8828cf65d"
name = "API-Products"
application_url = "http://localhost:3000"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,write_files,write_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "http://localhost:3000/callback" ]
